project_id = "aefktiqfjvmapeyshwey"

[functions.mp-webhook]
verify_jwt = false

[functions.mp-create-pix]
verify_jwt = false

[functions.mp-check-payment]
verify_jwt = false

[functions.proxy-stream]
verify_jwt = false
